### ISSUE TITLE
Improve error message when a native datetime object fails to json_encode

### ISSUE THREAD

**Issue by dwnoble** [humangeo/rawes#17]

**Comment by mishu-** [comment]
Do you have an example for this?

**Comment by dwnoble** [comment]
Yes indeed.  rawes by default requires timezones to be attached to datetime objects.  If they aren't attached, you get an error like:

``` python
import rawes
import datetime
es = rawes.Elastic()
utc_now = datetime.datetime.utcnow()
es.post("rawes_test") # Create a sample index
es.post("rawes_test/mytype",data={
    "name" : "dan",
    "created" : utc_now
}
```

```
Traceback (most recent call last):
...stack trace ...
ValueError: astimezone() cannot be applied to a naive datetime
```

This error seems a little confusing to me.  Something better might be: "Default json encoder requires datetime object to have an associated timezone (tzinfo)"
