### ISSUE TITLE
elasticsearch timeout

### ISSUE THREAD

**Issue by Dieterbe** [humangeo/rawes#19]
in an Elastic object, sometimes the self.connection will timeout:

```
File "/home/dieter/workspaces/eclipse/graph-explorer/structured_metrics/__init__.py", line 174, in assure_index
    self.es.post('graphite_metrics', data=body)
  File "/home/dieter/workspaces/eclipse/graph-explorer/structured_metrics/rawes/rawes/elastic.py", line 61, in post
    return self.request('post', path, **kwargs)
  File "/home/dieter/workspaces/eclipse/graph-explorer/structured_metrics/rawes/rawes/elastic.py", line 83, in request
    return self.connection.request(method, new_path, **kwargs)
  File "/home/dieter/workspaces/eclipse/graph-explorer/structured_metrics/rawes/rawes/http_connection.py", line 40, in request
    response = self.session.request(method, "/".join((self.url, path)), **args)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 357, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 460, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 360, in send
    raise Timeout(e)
Timeout: HTTPConnectionPool(host='graphiteserver', port=9202): Read timed out. (read timeout=30)
```

right now as a user we have to catch the Timeout error and create a new Elastic object (unless I'm missing something)
suggested solutions:
- add a reconnect() method to the Elastic class, have users catch the error and call the reconnect method.
- automatically catch that specific error in the Elasticsearch class and handle it, invisible to the user. (would probably still need to keep track of how many retried attempts and bubble up the error after X attempts)

**Comment by dwnoble** [comment]
Hmmm.. I'm not quite following.  In some quick tests I ran i didn't find that hitting a timeout required me to create a new rawes.Elastic object.

``` python
import rawes
import requests.exceptions


es = rawes.Elastic("http://localhost:9200/")

try:
    # Get rawes to timeout
    es.get("myindex/_search",timeout=0.0000001)
except requests.exceptions.Timeout as t:
    print "Timed out: ", str(t)

# Don't set the timeout this time, should work
print es.get("myindex/_search")

```

Am I off the mark somehow?

**Comment by Dieterbe** [comment]
okay so what i'm seeing is that as soon as 1 request times out, all the subsequent ones do too. it's as if the timeout error affects all future requests, not just the current one, and the connection breaks and doesn't recover.

right now when this happens, i restart my program.
creating a new Elastic object (and hence a new connection) is something I assume would fix this, but I haven't actually tried it.

**Comment by dwnoble** [comment]
Interesting - can you tell me a little more about your environment so I can try to replicate? version of elasticsearch, version of python requests, https://github.com/vimeo/graph-explorer version < https://github.com/vimeo/graph-explorer/commit/ebb5b49dee70a96552cdcd035f4452838d8551c5 - no hard feelings :)

also is it possible for you to reliably replicate this by setting rawes timeout to something smaller than 30 seconds (otherwise i imagine i'll have to load in a bunch of timeseries data to get see the 30 second timeout)

**Comment by Dieterbe** [comment]
so basically the last commit before https://github.com/vimeo/graph-explorer/commit/ebb5b49dee70a96552cdcd035f4452838d8551c5 , you can also see the version of rawes and requests in the bottom of that diff.  ES is 0.90.2
the GE machine and the ES machine are also in different datacenters, connected over a vpn which may be to blame.

i reported this issue because i thought you would know what it's about and fix it easily, but 
since i'm the only one reporting this, and the issue might be on my end, and i'm switching to elasticsearch-py anyway, maybe we shouldn't bother anymore.

**Comment by dwnoble** [comment]
Haven't been able to replicate yet - will keep an eye on this though
