### ISSUE TITLE
License for RAWES

### ISSUE THREAD

**Issue by neogenix** [humangeo/rawes#2]
I'd love to start using this for a project I have, but alas there's no License included, can you perhaps add one (assuming this is OpenSource) ? If you need any pointers, feel free to ping me!

**Comment by dwnoble** [comment]
Good call with adding a license.  I ended up going with the Apache 2.0 License - it seems relatively open, and is used by elasticsearch.

**Comment by neogenix** [comment]
Thanks for knocking this out! Did a pull request to add some missing stuff from the LICENSE!
