### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by apert** [humangeo/rawes#23]
Hi , im very new in ELK stack and python, i found that this is very interesting to used , do you mind provide tutorial how to use this, i just can install rawes but don't know what to do next step?(newbie)
1. PC 1 with elk stack
2. PC 2 with database that has log inside

i want my elk stack on PC 1 pull table log inside PC 2 using rawes, do you mind give me tip :)

**Comment by bernardosgr** [comment]
Hi apert,

Without know anything else about your setup, I'd say you have to approach your situation in the folloeing manner:
1) Develop an understanding of logstash and how it can pull/push logs into ES.
2) Possibly develop some agent to periodically retrieve data from the tables you mention
3) Normalize/setup how LogStash is going to format and push your data.
