### ISSUE TITLE
Is python-dateutil version 2.1 required?

### ISSUE THREAD

**Issue by dylanvaughn** [humangeo/rawes#6]
I am using this in a project along with celery, which specifies python-dateutil>=1.5,<2.0 as a dependency.  This makes it hard to use this library since it specifies python-dateutil==2.1, basically limiting this library to Py3K.

Is version 2.1 required for some reason?

Thanks!  Dylan

**Comment by dwnoble** [comment]
Hey Dylan,

Thanks for pointing out this issue.  There was no reason for rawes to depend strictly on version 2.1 of python-dateutil, so I relaxed that requirement to require python-dateutil>=1.0.  

Let me know if this works for you,
Dan

**Comment by dylanvaughn** [comment]
That's great - thank you!
