### ISSUE TITLE
would be nice to incorporate some error handling when requests are not successful

### ISSUE THREAD

**Issue by deanmalmgren** [humangeo/rawes#8]
I end up writing things like this a lot:

```
result = es.get("something in here")
if result.has_key("ok") and result["ok"]:
    print "yippee"
else:
    raise Exception(str(result))
```

It would be really convenient to make this more "pythonic" with Exceptions that get raised within the `get`/`post`/`put`/`delete` methods in the event of any error to make it easier to handle these problems.

**Comment by dwnoble** [comment]
I like this idea - my code is littered with similar conditional statements.  I'll throw this into a new rawes version in the next few days.  I'm thinking the various request methods will throw an exception any time an HTTP status code of >= 400 is returned from elasticsearch.

**Comment by dwnoble** [comment]
OK, i took a crack at addressing this issue by adding a new optional parameter 'except_on_error' to the rawes.Elastic constructor.  you can now do something like:

``` python
from rawes.elastic_exception import ElasticException
es = rawes.Elastic('localhost:9200', except_on_error=True)
try:
    es.get('invalid_index/invalid_type/123')
except ElasticException as e:
    # since our index is invalid, this exception handler will run  
    print e.result 
    # prints: {u'status': 404, u'error': u'IndexMissingException[[invalid_index] missing]'}
    print e.status_code
    # prints: 404
```

I'm not completely in love with this design - i think it's a little weird passing an argument into the constructor specifying that you want exceptions thrown.  I mostly just didn't want to break existing applications.  Perhaps throwing exceptions will be the default behavior in rawes 1.0!

**Comment by deanmalmgren** [comment]
That looks pretty good; thanks for implementing! 

I agree that the `except_on_error` flag seems a little clunky, but its better than nothing for the time being.

**Comment by Dieterbe** [comment]
+1 for defaulting to exceptions
